version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: nock
    versions:
    - 13.0.10
    - 13.0.6
    - 13.0.7
    - 13.0.8
    - 13.0.9
  - dependency-name: "@types/koa"
    versions:
    - 2.11.7
    - 2.11.8
    - 2.13.0
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: awilix
    versions:
    - 4.3.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: chalk
    versions:
    - 4.1.0
